### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by elycetacani** [jun3rd/college#34]
![screen shot 2018-04-30 at 8 03 41 am](https://user-images.githubusercontent.com/16247690/39434302-0e65cda4-4c4d-11e8-954e-9fd7931a2b6c.png)
I do not know why there is a second line of the exact same college...

**Comment by jun3rd** [comment]
Good catch. I didn't notice this at first. Solution was to put a quick if-else statement in the JavaScript.
